name: 'Pull Request Auto-Assignment for AppDev'
description: 'Adds pull request reviewers and assignees for AppDev'
author: 'Michael Obrycki'

inputs:
  githubToken:
    description: The GitHub token from the workflow context
    required: true
  additionalAccessPat:
    description: A PAT that will be used for additional access
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
