name: Pull Request Auto Assignment

on:
  pull_request:
    branches:
      - develop

jobs:
  pull-request-assignment:
    name: Pull Request Auto Assignment
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Auto Assignment
        uses: plantemoran-appdev/gh-action-pr-auto-assign@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          additionalAccessPat: ${{ secrets.GH_ACTION_AUTO_ASSIGN_PAT }}
