# since we're using vercel/ncc to package up our action (so we don't have to commit node_modules)
# we need to ensure that the dist/ files have been created/updated properly

name: Validate dist/ files

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'dist/**'

  pull_request:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'dist/**'

  workflow_dispatch:

jobs:
  validate-dist-files:
    name: Validate dist/ files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run prepare

      - name: Compare the expected and actual dist/ directories
        id: diff-dist-files
        run: |
          if [ "$(git diff --ignore-all-space dist/ | wc -l)" -gt "0" ]; then
            echo "Updated dist/ files have not been committed. See status below:"
            git diff
            exit 1
          fi

      # if diff-dist-files failed, upload the expected diff/ as an artifact
      - name: Upload expected dist/ files
        uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff-dist-files.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
