# since we're using vercel/ncc to package up our action (so we don't have to commit node_modules)
# we need to ensure that the builtAction/ files have been created/updated properly

name: Validate builtAction/ files

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'builtAction/**'

  pull_request:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'builtAction/**'

  workflow_dispatch:

jobs:
  validate-built-files:
    name: Validate builtAction/ files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the action
        run: npm run build-action

      - name: Compare the expected and actual builtAction/ directories
        id: diff-built-files
        run: |
          if [ "$(git diff --ignore-all-space builtAction/ | wc -l)" -gt "0" ]; then
            echo "Updated builtAction/ files have not been committed. See status below:"
            git diff
            exit 1
          fi

      # if diff-built-files failed, upload the expected diff/ as an artifact
      - name: Upload expected builtAction/ files
        uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff-built-files.conclusion == 'failure' }}
        with:
          name: builtAction
          path: builtAction/
